spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        same-site: lax

  shutdown: graceful
  forward-headers-strategy: native

app:
  security:
    csp: >-
      default-src 'self';
      img-src 'self' https: data:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      script-src 'self';
      connect-src 'self';
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'none';
      form-action 'self';
    csrfEnabled: true
    cspReportOnly: false